// <auto-generated />
using System;
using MedicalClinic.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalClinic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260426170709_AddReminderSent")]
    partial class AddReminderSent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Intentionally minimal - this migration is a no-op
        }
    }
}
